# Generated by Django 5.1.2 on 2025-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], max_length=50)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature_header', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('replay_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
    ]
