# Generated by Django 5.1.2 on 2025-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouscartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
